version: '2'
services:
  admin-server:
    image: syscomiddleware/oracle-soa-domain-admin-server:osb-compact-domain-soa-qs-12.1.3-jdk7-centos7
    ports:
     - "7001:7001"
    links:
     - soa-database
  soa-database:
    image: syscomiddleware/oracle-soa-domain-database:osb-compact-domain-soa-qs-12.1.3-basic-11.2.0.4-se-oraclelinux6.7
